<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestWithInvalidInput</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9ece2d06-def1-459e-85cd-24b3776d1d9e</testSuiteGuid>
   <testCaseLink>
      <guid>0f01f091-1a6c-4f56-850a-3814c69cd77f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_LoginForm/TC04_VerifyWrongDataInputErrorMessage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f61a162-6122-44a5-9336-764cedd52259</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0012d8c-e58f-4f20-8fa9-c89581456084</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f28b119d-4b39-4415-a0bd-d17e954eec50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67a5872f-7c35-4f9f-83b9-e6340ab71564</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_LoginForm/TC05_VerifyInvalidInputMutipleTimes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>838eacbc-97e8-453f-b04c-aabbd5ac2eb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6889d19-dc93-44b2-a503-cebb70ac6d92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6fae40a-d600-4f37-85ba-8baed49c35e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1d80efb-48f8-4c11-906d-0c9c06e04f4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_LoginForm/TC06_VerifyEmptyInput</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6b13a8b-780b-4fa5-92be-3c785a9e7151</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf5136c1-141e-4739-bd5d-a27a65509e9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a85d190-cf08-46fc-b394-1a77d4997ee0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>99f83ad2-e6cb-488b-aed9-a80df2eb5de6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_LoginForm/TC07_VerifyInvalidInputFormat</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c9c3f68-65c9-4db3-883d-7737020f740b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe98945-7fc1-48bd-b508-58e5f9ba05ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30d01074-3eb9-4a62-b938-06529f6decc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85b91a33-a47d-47c5-a77b-b9199d9a4cba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_LoginForm/TC08_VerifyInputLength</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58b3d42f-4d32-498a-b271-ad4bd7a03c24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>021c0588-9ad0-4a56-90d1-2a75fb9d2151</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05c59ce8-d7dd-4e96-885f-5740392b2f06</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
